const arrayOfLanguages = {
  ru: {
    language: "ru",
    title: "Нурлыбек Нуржан",
    home: "Главная",
    about: "Обо мне",
    skills: "Навыки",
    works: "Работы",
    contact: "Контакты",
    hi: "Привет, меня зовут",
    myName: "Нурлыбек Нуржан",
    me: "Я -",
    firstWord: "Frontend Разработчик",
    secondWord: "Верстальщик",
    thirdWord: "Web Разработчик",
    cvOpen: "Открыть резюме",
    contactMe: "Связаться со мной",
    siteBtn: "Web-Сайты",
    interBtn: "Интерактивы",
    workCode: "Код",
    workSite: "Сайт",
    aboutMe: "Я Нуржан",
    aboutDesc1: "Готов помочь вашему бизнесу",
    aboutDesc2: "качественными услугами",
    aboutDesc3: "Frontend Разработчика в",
    aboutDesc4: "кратчайшие сроки",
    aboutText:
      "Я создаю современные сайты различного формата и несу ответственность за адаптивную, кроссбраузерную верстку и разработку сайтов, комфортную как визуально так и на практике с помощью качественно подобранных решений адаптива и инетрактивов. Подробнее обо мне в моём",
    aboutCv: "резюме",
    profFirst: "Года опыта в Frontend Разработке",
    profSecond: "Senior Frontend Разработчика были моими менторами",
    profThird: "Командных проектов было реализовано",
    callMe: "Связаться со мной",
    name: "Имя",
    email: "Электронная почта",
    subject: "Тема обращения",
    message: "Сообщение",
    send: "Отправить",
  },
  es: {
    language: "es",
    title: "Nurlybek Nurzhan",
    home: "Inicio",
    about: "Sobre mi",
    skills: "Habilidades",
    works: "Trabajos",
    contact: "Contacto",
    hi: "Hola, me llamo",
    myName: "Nurlybek Nurzhan",
    me: "Yo soy",
    firstWord: "Desarrollador Frontend",
    secondWord: "Maquetador",
    thirdWord: "Desarrollador web",
    cvOpen: "Abrir currículum",
    contactMe: "Contacte conmigo",
    siteBtn: "Sitios Web",
    interBtn: "Interactiva",
    workCode: "Código",
    workSite: "Sitio",
    aboutMe: "Soy Nurzhan",
    aboutDesc1: "Listo para ayudar a su empresa con",
    aboutDesc2: "servicios de calidad",
    aboutDesc3: "de Frontend Developer lo",
    aboutDesc4: "antes posible",
    aboutText:
      "Creo sitios web modernos en varios formatos y soy responsable de la maquetación responsive y cross-browser, así como del desarrollo de sitios fáciles de usar tanto desde el punto de vista visual como práctico, con soluciones adaptativas e interactivas de calidad. Más sobre mí en mi",
    aboutCv: "curriculum vitae",
    profFirst: "Años de experiencia en Desarrollo Frontend",
    profSecond: "Senior Frontend Developer fue mi mentor",
    profThird: "Se ejecutaron proyectos en equipo",
    callMe: "Contacte conmigo",
    name: "Nombre",
    email: "Correo electrónico",
    subject: "Asunto",
    message: "Mensaje",
    send: "Enviar mensaje",
  },
  ger: {
    language: "ger",
    title: "Nurlybek Nurzhan",
    home: "Start",
    about: "Über mich",
    skills: "Faehigkeiten",
    works: "Arbeiten",
    contact: "Kontakt",
    hi: "Hallo, mein Name ist",
    myName: "Nurlybek Nurzhan",
    me: "Ich bin",
    firstWord: "Frontend Entwickler",
    secondWord: "Layout Designer",
    thirdWord: "Web Entwickler",
    cvOpen: "Lebenslauf öffnen",
    contactMe: "Kontaktaufnahme",
    siteBtn: "Web-Seiten",
    interBtn: "Interaktive",
    workCode: "Code",
    workSite: "Site",
    aboutMe: "Ich bin Nurzhan",
    aboutDesc1: "Bereit, Ihr Unternehmen zu unterstützen mit",
    aboutDesc2: "Qualitätsleistungen",
    aboutDesc3: "von Frontend Developer so",
    aboutDesc4: "schnell wie möglich",
    aboutText:
      "Ich erstelle moderne Websites in verschiedenen Formaten und bin verantwortlich für responsives, browserübergreifendes Layout und die Entwicklung von Websites, die sowohl visuell als auch praktisch benutzerfreundlich sind, mit hochwertigen adaptiven und interaktiven Lösungen. Mehr über mich in meinem",
    aboutCv: "rebenslauf",
    profFirst: "Jahrelange Erfahrung in der Frontend-Entwicklung",
    profSecond: "Senior Frontend Developer war mein Mentor",
    profThird: "Team-Projekte wurden durchgeführt",
    callMe: "Kontaktieren Sie mich",
    name: "Name",
    email: "Email",
    subject: "Thema",
    message: "Nachricht",
    send: "Nachricht senden",
  },
  en: {
    language: "en",
    title: "Nurlybek Nurzhan",
    home: "Home",
    about: "About Me",
    skills: "Skills",
    works: "Works",
    contact: "Contact",
    hi: "Hi, my name is",
    myName: "Nurlybek Nurzhan",
    me: "I'm",
    firstWord: "Frontend Developer",
    secondWord: "Layout Designer",
    thirdWord: "Web Developer",
    cvOpen: "Open CV",
    contactMe: "Contact me",
    siteBtn: "Web-Sites",
    interBtn: "Interactive",
    workCode: "Code",
    workSite: "Site",
    aboutMe: "I am Nurzhan",
    aboutDesc1: "Ready to help your business with",
    aboutDesc2: "quality services",
    aboutDesc3: "of Frontend Developer as",
    aboutDesc4: "quickly as possible",
    aboutText:
      "I create modern websites in various formats and am responsible for responsive, cross-browser layout and developing sites that are both visually and practically user-friendly with quality adaptive and interactive solutions. More about me in my",
    aboutCv: "resume",
    profFirst: "Years of experience in Frontend Development",
    profSecond: "Senior Frontend Developer was my mentor",
    profThird: "Team projects were implemented",
    callMe: "Contact me",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    send: "Send message",
  },

  fr: {
    language: "fr",
    title: "Nurlybek Nurzhan",
    home: "Accueil",
    about: "À propos",
    skills: "Compétences",
    works: "Travaux",
    contact: "Contact",
    hi: "Bonjour, je m'appelle",
    myName: "Nurlybek Nurzhan",
    me: "Je suis",
    firstWord: "Développeur Frontend",
    secondWord: "Maquettes",
    thirdWord: "Développeur Web",
    cvOpen: "Ouvert CV",
    contactMe: "Contactez-moi",
    siteBtn: "Web-Sites",
    interBtn: "Interactif",
    workCode: "Code",
    workSite: "Site",
    aboutMe: "Je suis Nurzhan",
    aboutDesc1: "Prêt à aider votre entreprise avec des",
    aboutDesc2: "services de qualité",
    aboutDesc3: "de Développeur Frontend dans",
    aboutDesc4: "les plus brefs délais",
    aboutText:
      "Je crée des sites web modernes dans différents formats et je suis responsable de la mise en page responsive et cross-browser et du développement de sites qui sont à la fois visuellement et pratiquement conviviaux avec des solutions adaptatives et interactives de qualité. En savoir plus sur moi dans mon",
    aboutCv: "résumé",
    profFirst:
      "Des années d'expérience dans le développement d'applications frontales",
    profSecond: "Mon mentor était un développeur frontal senior.",
    profThird: "Des projets d'équipe ont été mis en œuvre",
    callMe: "Contactez-moi",
    name: "Nom",
    email: "Courriel",
    subject: "Sujet",
    message: "Message",
    send: "Envoyer un message",
  },
};
